import { useEffect, useRef, useState } from "react";
import { ArrowLeft, Check, FilePlus2, KeyRound, MoreHorizontal, PanelLeftClose, Pencil, Plus, RefreshCw, Send, Settings2, Square, Trash2, X } from "lucide-react";
import type { AppSettings, Conversation, Effort, Message, Model, Provider } from "../domain/types";
import { mockStore } from "../services/mockStore";
import { ChatError, streamChat } from "../services/chatApi";
import { providerApi, ProviderError, validateProviderInput } from "../services/providerApi";
import { secretVault } from "../services/nativeVault";

type View = "chat" | "settings";
type SettingsSection = "providers" | "appearance";
type FormState = { id?: string; name: string; baseUrl: string; protocol: Provider["protocol"]; secret: string };
const emptyForm: FormState = { name: "Gonka Router", baseUrl: "https://api.gonkarouter.io/v1", protocol: "openai-compatible", secret: "" };
const now = () => new Date().toISOString();

export function App() {
  const [collapsed, setCollapsed] = useState(false); const [view, setView] = useState<View>("chat");
  const [providers, setProviders] = useState<Provider[]>([]); const [models, setModels] = useState<Model[]>([]);
  const [conversations, setConversations] = useState<Conversation[]>([]); const [currentId, setCurrentId] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([]); const [settings, setSettings] = useState<AppSettings>({ theme: "dark" });

  const reload = async () => { setProviders(await mockStore.listProviders()); setModels(await mockStore.listModels()); setConversations(await mockStore.listConversations()); setSettings(await mockStore.getSettings()); };
  const createConversation = async () => { const conversation: Conversation = { id: crypto.randomUUID(), title: "New conversation", effort: "medium", createdAt: now(), updatedAt: now() }; await mockStore.saveConversation(conversation); await reload(); setCurrentId(conversation.id); setMessages([]); setView("chat"); return conversation; };
  useEffect(() => { void (async () => { await reload(); const list = await mockStore.listConversations(); if (list[0]) setCurrentId(list[0].id); })(); }, []);
  useEffect(() => { if (currentId) void mockStore.listMessages(currentId).then(setMessages); }, [currentId]);
  const current = conversations.find(item => item.id === currentId) ?? null;
  const updateSettings = async (next: AppSettings) => { await mockStore.saveSettings(next); setSettings(next); };
  const rename = async (conversation: Conversation) => { const title = window.prompt("Rename conversation", conversation.title)?.trim(); if (!title) return; await mockStore.saveConversation({ ...conversation, title, updatedAt: now() }); await reload(); };
  const remove = async (conversation: Conversation) => { if (!window.confirm(`Delete “${conversation.title}”?`)) return; await mockStore.deleteConversation(conversation.id); const remaining = (await mockStore.listConversations()).filter(item => item.id !== conversation.id); await reload(); setCurrentId(remaining[0]?.id ?? null); setMessages([]); };
  return <main className={collapsed ? "shell collapsed" : "shell"} data-theme={settings.theme}>
    <aside className="sidebar" aria-label="Conversations"><div className="side-top"><button className="icon-button" onClick={() => setCollapsed(true)} aria-label="Masquer la barre latérale"><PanelLeftClose size={17}/></button><span>Solar</span></div><button className="new-thread" onClick={() => void createConversation()}><FilePlus2 size={16}/><span>New conversation</span></button><div className="thread-label">Recent</div><nav>{conversations.map(conversation => <div className={conversation.id === currentId ? "thread-wrap active" : "thread-wrap"} key={conversation.id}><button className="thread" onClick={() => { setCurrentId(conversation.id); setView("chat"); }}><span>{conversation.title}</span></button><button className="thread-action" onClick={() => void rename(conversation)} aria-label={`Rename ${conversation.title}`}><Pencil size={13}/></button></div>)}</nav><button className="settings" onClick={() => setView("settings")}><Settings2 size={16}/><span>Settings</span></button></aside>
    <section className="workspace"><header className="header"><button className="reveal icon-button" onClick={() => setCollapsed(false)} aria-label="Afficher la barre latérale"><PanelLeftClose size={17}/></button><span className="title">{view === "chat" ? current?.title ?? "New conversation" : "Settings"}</span>{view === "chat" && current ? <button className="icon-button" onClick={() => void remove(current)} aria-label="Delete conversation"><Trash2 size={17}/></button> : <span className="header-spacer"/>}</header>
      {view === "chat" ? <ChatView current={current} messages={messages} providers={providers} models={models} onCreated={createConversation} onConversation={async (conversation) => { await mockStore.saveConversation(conversation); await reload(); }} onMessages={setMessages} onSettings={() => setView("settings")} /> : <SettingsView providers={providers} models={models} settings={settings} updateSettings={updateSettings} reload={reload} onBack={() => setView("chat")} />}
    </section>
  </main>;
}

function ChatView({ current, messages, providers, models, onCreated, onConversation, onMessages, onSettings }: { current: Conversation | null; messages: Message[]; providers: Provider[]; models: Model[]; onCreated: () => Promise<Conversation>; onConversation: (value: Conversation) => Promise<void>; onMessages: (value: Message[]) => void; onSettings: () => void }) {
  const [draft, setDraft] = useState(""); const [error, setError] = useState(""); const [streaming, setStreaming] = useState(false); const controller = useRef<AbortController | null>(null);
  const conversation = current; const selectedModel = models.find(model => model.id === conversation?.modelId); const provider = providers.find(item => item.id === conversation?.providerId) ?? (selectedModel ? providers.find(item => item.id === selectedModel.providerId) : undefined);
  const saveMessages = async (next: Message[]) => { onMessages(next); for (const message of next) await mockStore.saveMessage(message); };
  const changeModel = async (modelId: string) => { const model = models.find(item => item.id === modelId); const base = conversation ?? await onCreated(); if (!model) return; await onConversation({ ...base, modelId, providerId: model.providerId, updatedAt: now() }); };
  const send = async () => {
    const content = draft.trim(); if (!content || streaming) return; setError(""); const active = conversation ?? await onCreated();
    const model = models.find(item => item.id === active.modelId); const activeProvider = providers.find(item => item.id === (active.providerId ?? model?.providerId));
    if (!activeProvider) { setError("Configure puis sélectionne un fournisseur et un modèle avant d’envoyer un message."); return; }
    if (!model) { setError("Sélectionne un modèle avant d’envoyer un message."); return; }
    const user: Message = { id: crypto.randomUUID(), conversationId: active.id, role: "user", content, status: "completed", createdAt: now(), order: messages.length };
    const assistant: Message = { id: crypto.randomUUID(), conversationId: active.id, role: "assistant", content: "", status: "streaming", createdAt: now(), order: messages.length + 1 };
    const title = active.title === "New conversation" ? content.slice(0, 48) : active.title;
    const updated = { ...active, title: title || "New conversation", providerId: activeProvider.id, modelId: model.id, updatedAt: now() }; await onConversation(updated); setDraft(""); setStreaming(true); await saveMessages([...messages, user, assistant]);
    controller.current = new AbortController(); let latest = assistant;
    try { await streamChat({ provider: activeProvider, model: model.providerModelId ?? model.id, messages: [...messages, user], effort: updated.effort, vault: secretVault, signal: controller.current.signal, onDelta: (delta) => { latest = { ...latest, content: latest.content + delta }; const next = [...messages, user, latest]; onMessages(next); void mockStore.saveMessage(latest); } }); latest = { ...latest, status: "completed" }; await saveMessages([...messages, user, latest]); }
    catch (reason) { const chatError = reason instanceof ChatError ? reason : new ChatError("Une erreur inattendue est survenue.", "network"); const interrupted = chatError.code === "interrupted"; latest = { ...latest, status: interrupted ? "interrupted" : "error", error: interrupted ? undefined : chatError.message }; await saveMessages([...messages, user, latest]); if (!interrupted) setError(chatError.message); }
    finally { controller.current = null; setStreaming(false); }
  };
  const stop = () => controller.current?.abort();
  return <><div className={messages.length ? "chat-scroll has-messages" : "chat-scroll"}>{messages.length === 0 ? <div className="canvas"><div className="welcome"><p className="eyebrow">SOLAR · LOCAL AI</p><h1>Local AI,<br/>without the noise.</h1><p className="intro">Choose a model, then start a conversation.</p><button className="inline-link" onClick={onSettings}>Configure a model provider <ArrowLeft size={14} className="link-arrow"/></button></div></div> : <div className="message-list">{messages.map(message => <article className={`message ${message.role}`} key={message.id}><div className="message-role">{message.role === "user" ? "You" : "Solar"}{message.status === "streaming" ? " · generating" : ""}</div><div className="message-content">{message.content || (message.status === "streaming" ? <span className="cursor">●</span> : "")}</div>{message.error && <p className="message-error">{message.error}</p>}</article>)}</div>}</div>
    <div className="composer-wrap">{error && <p className="composer-error" role="alert">{error}</p>}<div className="composer"><textarea value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder="Message Solar…" rows={1} disabled={streaming}/><div className="composer-footer"><div className="composer-controls"><select className="model-control" aria-label="Choisir un modèle" value={conversation?.modelId ?? ""} onChange={event => void changeModel(event.target.value)} disabled={streaming}><option value="">No model selected</option>{models.filter(model => model.enabled).map(model => <option key={model.id} value={model.id}>{model.name}</option>)}</select><select className="effort-control" value={conversation?.effort ?? "medium"} aria-label="Niveau d’effort" onChange={event => { if (conversation) void onConversation({ ...conversation, effort: event.target.value as Effort, updatedAt: now() }); }} disabled={streaming}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div>{streaming ? <button className="stop" type="button" onClick={stop}><Square size={13} fill="currentColor"/> Stop</button> : <button className="send" type="button" onClick={() => void send()} disabled={!draft.trim() || !selectedModel} aria-label="Envoyer le message"><Send size={16}/></button>}</div></div><p className="hint">Enter to send · Shift + Enter for a new line</p></div></>;
}

function SettingsView({ providers, models, settings, updateSettings, reload, onBack }: { providers: Provider[]; models: Model[]; settings: AppSettings; updateSettings: (next: AppSettings) => Promise<void>; reload: () => Promise<void>; onBack: () => void }) {
  const [section, setSection] = useState<SettingsSection>("providers"); const [editing, setEditing] = useState<FormState | null>(null);
  return <div className="settings-page"><div className="settings-heading"><div><button className="back-button" onClick={onBack}><ArrowLeft size={15}/> Back to chat</button><p className="eyebrow">SETTINGS</p><h1>Settings</h1></div></div><div className="settings-layout"><nav className="settings-nav"><button className={section === "providers" ? "selected" : ""} onClick={() => setSection("providers")}>Model providers</button><button className={section === "appearance" ? "selected" : ""} onClick={() => setSection("appearance")}>Appearance</button></nav><div className="settings-content">{section === "appearance" ? <Appearance settings={settings} updateSettings={updateSettings} /> : <><div className="section-title"><div><h2>Model providers</h2><p>Connect a compatible API and choose its models.</p></div><button className="primary-button" onClick={() => setEditing({ ...emptyForm })}><Plus size={16}/> Add provider</button></div>{editing ? <ProviderForm initial={editing} onDone={async () => { setEditing(null); await reload(); }} onCancel={() => setEditing(null)} /> : <ProviderList providers={providers} models={models} setEditing={setEditing} reload={reload} />}</>}</div></div></div>;
}

function Appearance({ settings, updateSettings }: { settings: AppSettings; updateSettings: (next: AppSettings) => Promise<void> }) { return <div><div className="section-title"><div><h2>Appearance</h2><p>Choose the application theme.</p></div></div><div className="theme-options"><button className={settings.theme === "dark" ? "theme-card selected" : "theme-card"} onClick={() => void updateSettings({ ...settings, theme: "dark" })}><span className="theme-preview dark"/><span>Dark</span></button><button className={settings.theme === "light" ? "theme-card selected" : "theme-card"} onClick={() => void updateSettings({ ...settings, theme: "light" })}><span className="theme-preview light"/><span>Light</span></button></div></div>; }

function ProviderList({ providers, models, setEditing, reload }: { providers: Provider[]; models: Model[]; setEditing: (value: FormState) => void; reload: () => Promise<void> }) { if (!providers.length) return <div className="empty-card"><KeyRound size={22}/><h2>No providers yet</h2><p>Add Gonka Router to discover its models.</p></div>; return <div className="provider-list">{providers.map(provider => <ProviderCard key={provider.id} provider={provider} models={models.filter(model => model.providerId === provider.id)} setEditing={setEditing} reload={reload}/>)}</div>; }

function ProviderCard({ provider, models, setEditing, reload }: { provider: Provider; models: Model[]; setEditing: (value: FormState) => void; reload: () => Promise<void> }) { const [busy, setBusy] = useState<"test" | "refresh" | null>(null); const [notice, setNotice] = useState(""); const [manual, setManual] = useState(""); const run = async (kind: "test" | "refresh") => { setBusy(kind); setNotice(""); try { if (kind === "test") { await providerApi.test(provider, secretVault); setNotice("Connection successful."); } else { const found = await providerApi.discoverModels(provider, secretVault); for (const model of found) await mockStore.saveModel(model); await mockStore.saveProvider({ ...provider, connectionState: "connected", lastError: undefined }); await reload(); setNotice(`${found.length} model${found.length === 1 ? "" : "s"} found.`); } } catch (error) { setNotice(error instanceof ProviderError ? error.message : "Une erreur inattendue est survenue."); } finally { setBusy(null); } }; const addManual = async () => { const id = manual.trim(); if (!id) return; await mockStore.saveModel({ id, providerId: provider.id, name: id, capabilities: [], source: "manual", enabled: true }); setManual(""); await reload(); setNotice("Manual model added."); }; return <article className="provider-card"><div className="provider-head"><div><div className="provider-name"><span className={`status-dot ${provider.connectionState}`}/>{provider.name}</div><p className="provider-meta">{provider.protocol} · {provider.baseUrl}</p></div><div className="card-actions"><button className="small-button" onClick={() => setEditing({ id: provider.id, name: provider.name, baseUrl: provider.baseUrl, protocol: provider.protocol, secret: "" })}>Edit</button><button className="icon-button danger" onClick={() => void mockStore.deleteProvider(provider.id).then(reload)} aria-label={`Delete ${provider.name}`}><Trash2 size={16}/></button></div></div><div className="model-list">{models.length ? models.map(model => <div className="model-row" key={model.id}><span>{model.name}</span><span className="source-label">{model.source}</span></div>) : <p className="muted">No models discovered yet.</p>}</div><div className="provider-tools"><button className="small-button" onClick={() => void run("test")} disabled={Boolean(busy)}>{busy === "test" ? "Testing…" : "Test connection"}</button><button className="small-button" onClick={() => void run("refresh")} disabled={Boolean(busy)}><RefreshCw size={14}/>{busy === "refresh" ? "Refreshing…" : "Refresh models"}</button><div className="manual-add"><input aria-label="Manual model identifier" value={manual} onChange={event => setManual(event.target.value)} placeholder="model id"/><button className="small-button" onClick={() => void addManual()} disabled={!manual.trim()}><Plus size={14}/> Add manual</button></div></div>{notice && <p className="notice" role="status">{notice}</p>}</article>; }

function ProviderForm({ initial, onDone, onCancel }: { initial: FormState; onDone: () => Promise<void>; onCancel: () => void }) { const [form, setForm] = useState(initial); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const update = (key: keyof FormState, value: string) => setForm(current => ({ ...current, [key]: value })); const save = async () => { const issue = validateProviderInput(form.name, form.baseUrl, form.secret || (form.id ? "existing-secret" : "")); if (issue) { setError(issue); return; } setSaving(true); const id = form.id ?? crypto.randomUUID(); const secretRef = `provider:${id}`; const old = form.id ? (await mockStore.listProviders()).find(item => item.id === id) : undefined; if (form.secret) await secretVault.set(secretRef, form.secret); await mockStore.saveProvider({ id, name: form.name.trim(), baseUrl: form.baseUrl.trim().replace(/\/$/, ""), protocol: form.protocol, secretRef, enabled: true, connectionState: old?.connectionState ?? "unknown" }); setSaving(false); await onDone(); }; return <div className="form-card"><div className="form-head"><div><p className="eyebrow">PROVIDER CONFIGURATION</p><h2>{form.id ? "Edit provider" : "Add provider"}</h2></div><button className="icon-button" onClick={onCancel} aria-label="Close"><X size={18}/></button></div><label>Provider name<input value={form.name} onChange={event => update("name", event.target.value)} autoFocus/></label><label>Base URL<input value={form.baseUrl} onChange={event => update("baseUrl", event.target.value)} inputMode="url"/></label><label>Protocol<select value={form.protocol} onChange={event => update("protocol", event.target.value)}><option value="openai-compatible">OpenAI-compatible</option><option value="ollama">Ollama (prepared)</option></select></label><label>API key / secret<input type="password" value={form.secret} onChange={event => update("secret", event.target.value)} placeholder={form.id ? "Leave empty to keep current key" : "sk-…"}/><small><KeyRound size={13}/> Stored only in the secure vault in the native app.</small></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="small-button" onClick={onCancel}>Cancel</button><button className="primary-button" onClick={() => void save()} disabled={saving}>{saving ? "Saving…" : <><Check size={15}/> Save provider</>}</button></div></div>; }
