import assert from 'node:assert/strict';
import {parseArtifact,validateArtifact,exportArtifact,csvContent,displayAnswer} from '../src/services/artifacts.ts';
import {allowedPath,parseWorkChanges} from '../src/services/workProject.ts';
import {classify,artifactIntent,smartInstruction} from '../src/services/solarSmart.ts';
import {needsWeb,searchWeb,safeSourceUrl} from '../src/services/solarWeb.ts';
import {runtimeProfile,recommendModels} from '../src/services/performance.ts';
import {ToolRegistry,ToolExecutor} from '../src/services/toolRegistry.ts';
import {pullModel} from '../src/services/modelInstall.ts';
import {streamChat} from '../src/services/chatApi.ts';
const id='test';
assert.equal(artifactIntent('Crée une présentation de 6 diapositives sur Newton'),'slides');assert.equal(classify('Explique les fractions',false),'learning');assert.equal(smartInstruction('Code',false,false),'');assert.equal(needsWeb('Actualité cette semaine'),true);assert.equal(safeSourceUrl('javascript:alert(1)'),undefined);
const slides=validateArtifact({kind:'slides',title:'Newton',slides:Array.from({length:6},(_,i)=>({title:'Diapositive '+i,body:'Lois du mouvement'}))},id);
const pptx=await exportArtifact(slides,'pptx');assert(pptx.size>1000);assert.equal(new TextDecoder().decode(new Uint8Array(await pptx.arrayBuffer()).slice(0,2)),'PK');
const doc=validateArtifact({kind:'document',title:'Rapport',sections:[{title:'Conclusion',body:'Les données sont pertinentes.'}]},id);for(const format of ['pdf','docx']){const file=await exportArtifact(doc,format);const bytes=new Uint8Array(await file.arrayBuffer());assert(file.size>100);assert.equal(new TextDecoder().decode(bytes.slice(0,format==='pdf'?4:2)),format==='pdf'?'%PDF':'PK');}
const table=validateArtifact({kind:'table',title:'Chiffres',columns:['Nom','Valeur'],rows:[['A','=1+1'],['B','12']]},id);assert(csvContent(table).includes("'=1+1"));assert((await exportArtifact(table,'xlsx')).size>1000);
assert.throws(()=>validateArtifact({kind:'table',title:'Bad',columns:['A'],rows:[['A','B']]},id));assert.throws(()=>parseArtifact('pas de JSON',id));const updated=validateArtifact({...slides,title:'Newton corrigé'},id,slides);assert.equal(updated.id,slides.id);assert.equal(updated.revision,2);assert(!displayAnswer('Voici.\n```solar-artifact\n{"x":').includes('solar-artifact'));
assert(allowedPath('src/App.tsx'));for(const path of ['../secret','/etc/passwd','.env','src/../file','src/secrets.txt','src\\file'])assert(!allowedPath(path));assert.throws(()=>parseWorkChanges('```solar-changes\n{"changes":[{"path":"outside","content":"x"}]}\n```',{'src/a.ts':'old'}));assert.equal(parseWorkChanges('```solar-changes\n{"changes":[{"path":"src/a.ts","content":"new"}]}\n```',{'src/a.ts':'old'})[0].before,'old');
assert.equal(runtimeProfile('eco').keep_alive,'0');assert.equal(runtimeProfile().options.num_ctx,4096);assert(recommendModels(8*2**30).every(m=>m.memoryGB<8));
const registry=new ToolRegistry();registry.register({name:'read',description:'Read',parameters:{},permissions:['project.read'],execute:async()=>42});const executor=new ToolExecutor(registry);await assert.rejects(()=>executor.run('read',{},new Set(),new AbortController().signal));assert.equal(await executor.run('read',{},new Set(['project.read']),new AbortController().signal),42);
const oldFetch=globalThis.fetch;let requests=0;globalThis.fetch=async()=>{requests++;return new Response(JSON.stringify({results:[{title:'Source',url:'https://example.org/page',content:'Faits récents'},{title:'Unsafe',url:'file:///etc/passwd'}]}));};const settings={provider:'searxng',endpoint:'https://search.test/',mode:'auto',consent:true};const vault={get:async()=>null};const signal=new AbortController().signal;await assert.rejects(()=>searchWeb({...settings,consent:false},{text:'q'},vault,signal));const found=await searchWeb(settings,{text:'q'},vault,signal);assert.equal(found.sources.length,1);assert.equal((await searchWeb(settings,{text:'q'},vault,signal)).cached,true);assert.equal(requests,1);
globalThis.fetch=async()=>new Response('{"status":"pulling","completed":50,"total":100}\n{"status":"success"}\n');const progress=[];await pullModel('http://test','qwen3:4b',signal,p=>progress.push(p));assert.equal(progress[0].completed,50);globalThis.fetch=async()=>new Response('{"status":"pulling"}\n');await assert.rejects(()=>pullModel('http://test','qwen3:4b',signal,()=>{}));
let requestBody;globalThis.fetch=async(url,init)=>{requestBody=JSON.parse(init.body);return new Response('data: {"type":"content_block_delta","delta":{"type":"thinking_delta","thinking":"private"}}\n\ndata: {"type":"content_block_delta","delta":{"type":"text_delta","text":"Bonjour"}}\n\ndata: {"type":"message_stop"}\n\n');};let output='',stages=[];await streamChat({provider:{id:'a',name:'Anthropic',protocol:'anthropic',baseUrl:'https://api.test/v1',secretRef:'a'},model:'claude',vault:{get:async()=> 'fixture'},effort:'medium',messages:[{id:'u',role:'user',content:'Salut',status:'completed',attachments:[],conversationId:id,order:0,createdAt:''}],signal,onDelta:t=>output+=t,onActivity:s=>stages.push(s)});assert.equal(output,'Bonjour');assert(stages.includes('thinking'));assert.equal(requestBody.messages[0].role,'user');assert.equal(typeof requestBody.system,'string');globalThis.fetch=oldFetch;
console.log('evolution-contracts: ok (validated artifacts, real PPTX/PDF/DOCX/XLSX bytes, CSV safety, stable revisions, Work scope/proposals, tool permissions, Web consent/cache/sources, profiles, genuine pull progress, Anthropic streaming)');

const {extensionStore}=await import('../src/services/extensionStore.ts');const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};const temp={...slides,id:'temp-artifact',conversationId:'temp:session'};await extensionStore.save(temp);assert.equal((await extensionStore.listArtifacts('temp:session')).length,1);assert.equal(memory.size,0);await extensionStore.save(slides);await extensionStore.clearConversation(slides.conversationId);await extensionStore.save(slides);assert.equal((await extensionStore.listArtifacts(slides.conversationId)).length,0);console.log('extension-storage: ok (temporary artifacts stay in RAM, deleted conversations cannot be resurrected by late saves)');
