import assert from "node:assert/strict";
import { createSolarStore, emptyData, validateStoredData } from "../src/services/storageCore.ts";
import { buildSearchIndex, searchIndex, matchingParts } from "../src/services/search.ts";
import { shouldCompactPaste, pastedContent, draftMessage } from "../src/services/pastedContent.ts";
let disk = emptyData(); let fail = false;
const driver = { read: async () => structuredClone(disk), write: async data => { if (fail) throw new Error("disk full"); disk = structuredClone(data); } };
let store = createSolarStore(driver);
const conversation = { id:"c1", title:"Architecture navale", effort:"medium", createdAt:"2026-10-09T00:00:00Z", updatedAt:"2026-10-09T00:00:00Z" };
await store.saveConversation(conversation);
await store.saveMessage({id:"m1",conversationId:"c1",role:"assistant",content:"Une hélice efficace pour le bateau",status:"completed",createdAt:conversation.createdAt,order:0});
const raw = '  const code = "éè\\n";\n\treturn code;  \n'.repeat(40);
const attachment = pastedContent(raw); const draft = { conversationId:"c1",text:"Question\navec un retour",attachments:[attachment],updatedAt:conversation.updatedAt };
await store.saveDraft(draft);
store = createSolarStore(driver);
assert.deepEqual(await store.getDraft("c1"),draft,"draft and full attachments should survive restart");
assert.equal((await store.listMessages("c1"))[0].content,"Une hélice efficace pour le bateau");
const index = buildSearchIndex(await store.listConversations(),await store.listMessages("c1"));
assert.equal(searchIndex(index,"HELICE")[0].messageId,"m1","search must ignore case and accents");
assert.equal(searchIndex(index,"navale")[0].conversationId,"c1");
assert(matchingParts("Une hélice efficace","helice").some(part=>part.match && part.text==="hélice"));
assert(shouldCompactPaste(raw)); assert(!shouldCompactPaste("Texte court")); assert(shouldCompactPaste("x\n".repeat(30)));
assert(draftMessage(draft).includes(raw),"attached content must remain byte-for-byte intact in model input");
fail=true;await assert.rejects(store.saveDraft({...draft,text:"changed"}));assert.deepEqual(await store.getDraft("c1"),draft,"failed persistence must not erase saved state");fail=false;
await store.deleteConversation("c1");assert.equal(await store.getDraft("c1"),null);assert.equal((await store.listMessages("c1")).length,0);
await store.saveMessage({id:"orphan",conversationId:"c1",role:"assistant",content:"late",status:"completed",createdAt:conversation.createdAt,order:0});assert.equal((await store.listMessages("c1")).length,0,"late stream writes must not revive deleted chats");
assert.throws(()=>validateStoredData({...emptyData(),version:999}),/incompatible/);
await Promise.all([store.saveConversation({...conversation,id:"a"}),store.saveConversation({...conversation,id:"b"})]);assert.equal((await store.listConversations()).length,2,"serialized writes must preserve concurrent updates");
console.log("features-contract-tests: ok (storage, restart, drafts, attachments, failure recovery, offline search, paste, write ordering)");
