import assert from "node:assert/strict";
import { createSolarStore, emptyData, validateStoredData } from "../src/services/storageCore.ts";
import { buildSearchIndex, searchIndex, matchingParts } from "../src/services/search.ts";
import { shouldCompactPaste, pastedContent, draftMessage } from "../src/services/pastedContent.ts";
let disk = emptyData(); let fail = false;
const driver = { read: async () => structuredClone(disk), write: async data => { if (fail) throw new Error("disk full"); disk = structuredClone(data); } };
let store = createSolarStore(driver);
const conversation = { id:"c1", title:"Architecture navale", effort:"medium", createdAt:"2026-10-09T00:00:00Z", updatedAt:"2026-10-09T00:00:00Z" };
await store.saveConversation(conversation);
await store.saveMessage({id:"m1",conversationId:"c1",role:"assistant",content:"Une hélice efficace pour le bateau",status:"completed",createdAt:conversation.createdAt,order:0});
const raw = '  const code = "éè\\n";\n\treturn code;  \n'.repeat(40);
const attachment = pastedContent(raw); const draft = { conversationId:"c1",text:"Question\navec un retour",attachments:[attachment],updatedAt:conversation.updatedAt };
await store.saveDraft(draft);
store = createSolarStore(driver);
assert.deepEqual(await store.getDraft("c1"),draft,"draft and full attachments should survive restart");
assert.equal((await store.listMessages("c1"))[0].content,"Une hélice efficace pour le bateau");
const index = buildSearchIndex(await store.listConversations(),await store.listMessages("c1"));
assert.equal(searchIndex(index,"HELICE")[0].messageId,"m1","search must ignore case and accents");
assert.equal(searchIndex(index,"navale")[0].conversationId,"c1");
assert(matchingParts("Une hélice efficace","helice").some(part=>part.match && part.text==="hélice"));
assert(shouldCompactPaste(raw)); assert(!shouldCompactPaste("Texte court")); assert(shouldCompactPaste("x\n".repeat(30)));
assert(draftMessage(draft).includes(raw),"attached content must remain byte-for-byte intact in model input");
fail=true;await assert.rejects(store.saveDraft({...draft,text:"changed"}));assert.deepEqual(await store.getDraft("c1"),draft,"failed persistence must not erase saved state");fail=false;
await store.deleteConversation("c1");assert.equal(await store.getDraft("c1"),null);assert.equal((await store.listMessages("c1")).length,0);
await store.saveMessage({id:"orphan",conversationId:"c1",role:"assistant",content:"late",status:"completed",createdAt:conversation.createdAt,order:0});assert.equal((await store.listMessages("c1")).length,0,"late stream writes must not revive deleted chats");
assert.throws(()=>validateStoredData({...emptyData(),version:999}),/incompatible/);
await Promise.all([store.saveConversation({...conversation,id:"a"}),store.saveConversation({...conversation,id:"b"})]);assert.equal((await store.listConversations()).length,2,"serialized writes must preserve concurrent updates");
console.log("features-contract-tests: ok (storage, restart, drafts, attachments, failure recovery, offline search, paste, write ordering)");

const { conversationTitle, exportConversations } = await import("../src/services/conversationTools.ts");
assert.equal(conversationTitle("## Explique les étoiles\n\nUn second paragraphe"), "Explique les étoiles");
assert.equal(conversationTitle("```js\nconst x = 1;"), "Question sur du code");
assert.equal(conversationTitle("", 1), "Document à explorer");
assert(conversationTitle("abc ".repeat(100)).length <= 54);
await store.saveConversation({ ...conversation, id: "pinned", pinned: true, titleManuallyEdited: true });
await store.saveMessage({ id: "fav", conversationId: "pinned", role: "assistant", content: "```js\n  const x = 1;\n```\n\n|A|B|\n|-|-|\n|1|2|", modelName: "Modèle choisi", favorite: true, status: "completed", createdAt: conversation.createdAt, order: 1 });
await store.saveMessage({ id: "fav", conversationId: "pinned", role: "assistant", content: "Réponse enregistrée", modelName: "Modèle choisi", favorite: true, status: "completed", createdAt: conversation.createdAt, order: 1 });
assert.equal((await store.listMessages("pinned")).length, 1, "favorite must not duplicate messages");
const beforeTemporary = JSON.stringify(disk);
const temp = { ...conversation, id: "temp:private", temporary: true, pinned: true };
await store.saveConversation(temp);
await store.saveMessage({ id: "secret-temp", conversationId: temp.id, role: "assistant", content: "temporary private text", status: "completed", favorite: true, createdAt: conversation.createdAt, order: 0 });
await store.saveDraft({ ...draft, conversationId: temp.id, text: "temporary draft" });
assert.equal(JSON.stringify(disk), beforeTemporary, "temporary chat must never write to disk");
assert(!(await store.listConversations()).some(c => c.temporary));
assert.equal((await store.listTemporaryConversations())[0].pinned, false);
assert.equal((await store.listMessages(temp.id))[0].favorite, false);
assert.equal((await store.getDraft(temp.id)).text, "temporary draft");
const exported = exportConversations([{ conversation: temp, messages: await store.listMessages(temp.id) }, { conversation: (await store.listConversations()).find(c => c.id === "pinned"), messages: await store.listMessages("pinned") }], "md");
assert(!exported.includes("temporary private text")); assert(exported.includes("Modèle choisi"));
await store.deleteConversation(temp.id);
await store.saveMessage({ id: "late-temp", conversationId: temp.id, content: "late temporary", order: 1 });
assert.equal((await store.listMessages(temp.id)).length, 0);
store = createSolarStore(driver);
assert.equal((await store.listTemporaryConversations()).length, 0);
assert((await store.listConversations()).find(c => c.id === "pinned").pinned);
assert((await store.listMessages("pinned"))[0].favorite);
console.log("extended-feature-tests: ok (temporary privacy, pin/favorite restart, deduplication, export filtering, local titles)");
