const { chromium } = require(process.env.SOLAR_UI_NODE_MODULES ? require('node:path').join(process.env.SOLAR_UI_NODE_MODULES, 'playwright') : 'playwright');
const path=require('path');
const assert=(condition,label)=>{if(!condition)throw new Error(label);};
(async()=>{
 const {createServer}=await import('vite'); const server=await createServer({root:path.resolve(__dirname,'..'),server:{host:'127.0.0.1',port:1421,strictPort:true}});await server.listen();
 const browser=await chromium.launch({headless:true, ...(process.env.SOLAR_UI_CHROMIUM ? {executablePath:process.env.SOLAR_UI_CHROMIUM,args:process.env.SOLAR_UI_CHROMIUM_ARGS ? JSON.parse(process.env.SOLAR_UI_CHROMIUM_ARGS) : ['--no-sandbox']} : {})});
 const context=await browser.newContext({viewport:{width:1280,height:850},permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const provider={id:'test',name:'Fournisseur test',baseUrl:'https://example.test/v1',protocol:'openai-compatible',secretRef:'provider:test',enabled:true,connectionState:'connected'};
 const models=['test:fast','test:deep'].map((id,i)=>({id,providerId:'test',providerModelId:i?'deep':'fast',name:i?'Modèle approfondi':'Modèle rapide',enabled:true,source:'manual',capabilities:[]}));
 await page.addInitScript(({provider,models})=>{if(!localStorage.getItem('solar.providers.v2')){localStorage.setItem('solar.providers.v2',JSON.stringify([provider]));localStorage.setItem('solar.models.v2',JSON.stringify(models));localStorage.setItem('solar.preview-vault.v2',JSON.stringify({'provider:test':'non-sensitive-ui-fixture'}));}},{provider,models});
 let ollamaNames=['local-a','local-b'];let memoryFailure=false;let preloads=[];let requests=[];
 await page.route('**/solar-ollama/api/tags',r=>r.fulfill({json:{models:ollamaNames.map(name=>({name}))}}));
 await page.route('**/solar-ollama/api/ps',r=>r.fulfill({json:{models:[]}}));
 await page.route('**/solar-ollama/api/chat',async r=>{const body=JSON.parse(r.request().postData());if(body.messages.length===0){preloads.push(body);await r.fulfill(memoryFailure ? {status:500,json:{error:'insufficient memory'}} : {json:{done:true}});}else await r.fulfill({body:'{"message":{"content":"Réponse locale"},"done":true}\n',contentType:'application/x-ndjson'});});
 const answer='## Une réponse claire\n\nUn paragraphe avec **du texte important** et une hélice.\n\n```js\nconst solar = true;\n```\n\n| Modèle | Usage |\n| --- | --- |\n| Local | Privé |';
 await page.route('https://example.test/v1/chat/completions',async r=>{const body=JSON.parse(r.request().postData());requests.push(body);const action=body.messages[0].content.includes('Le champ « passage »');await new Promise(resolve=>setTimeout(resolve,action?300:1600));await r.fulfill({status:200,contentType:'text/event-stream',body:`data: ${JSON.stringify({choices:[{delta:{content:action?'Passage retravaillé.':answer}}]})}\n\ndata: [DONE]\n\n`}).catch(()=>{});});
 await page.goto('http://127.0.0.1:1421');await page.getByRole('heading',{name:'Local AI.'}).waitFor();
 const input=page.getByRole('textbox',{name:'Message à Solar'});await input.fill('Bonjour Solar');await page.getByRole('button',{name:'Choisir un modèle'}).click();await page.getByRole('button',{name:'Modèle rapide',exact:true}).click();assert(await input.inputValue()==='Bonjour Solar','draft lost on first model selection');
 await input.press('Shift+Enter');assert((await input.inputValue()).endsWith('\n'),'Shift Enter should add newline');await input.fill('Bonjour Solar');await input.press('Enter');await page.getByRole('button',{name:'Arrêter la génération'}).waitFor();
 await input.fill('Mon prochain message');await page.getByRole('button',{name:'Modèle rapide',exact:true}).click();await page.getByRole('button',{name:'Modèle approfondi',exact:true}).click();await page.getByRole('button',{name:'Niveau d’effort'}).click();await page.getByRole('button',{name:'Ultra Budget de réponse maximal'}).click();
 await page.getByRole('button',{name:'Envoyer le message',exact:true}).waitFor();assert(await input.inputValue()==='Mon prochain message','draft overwritten by stream');assert(requests[0].model==='fast' && requests[0].max_tokens===1024,'in-flight model snapshot changed');
 assert(await page.locator('.message-content h2').count()===1,'Markdown should render once');assert(await page.locator('.code-block code').count()===1,'code block should render');assert(await page.locator('.table-scroll table').count()===1,'GFM table should render');
 await page.screenshot({path:path.join(process.env.SOLAR_UI_SCREENSHOTS ?? '/tmp','solar-chat.png')});
 // Each of the three contextual actions streams separately and preserves the original message.
 for(const action of ['Simplifier','Développer','Corriger','Reformuler','Résumer']){
  await page.locator('.message.assistant .message-content p').first().evaluate(el=>{const range=document.createRange();range.selectNodeContents(el);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));});
  await page.getByRole('button',{name:action,exact:true}).click();await page.locator('.selection-result').getByRole('button',{name:'Insérer dans le champ'}).waitFor();assert(await page.locator('.selection-result').innerText().then(t=>t.includes('Passage retravaillé.')),'selection action result missing');assert(await page.locator('.message.assistant>.message-content').first().innerText().then(t=>t.includes('Une réponse claire')),'original answer changed');
 }
 await page.locator('.selection-result').getByRole('button',{name:'Copier',exact:true}).click();assert(await page.evaluate(()=>navigator.clipboard.readText())==='Passage retravaillé.','selection copy failed');
 await page.locator('.selection-result').getByRole('button',{name:'Insérer dans le champ'}).click();assert((await input.inputValue()).includes('Passage retravaillé.'),'selection insert failed');await page.getByRole('button',{name:'Fermer le résultat'}).click();
 // Smart paste preserves full text and persists with the per-chat draft.
 const raw='\tconst value = "é";  \n'.repeat(100);await input.evaluate((el,text)=>{const data=new DataTransfer();data.setData('text/plain',text);el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));},raw);
 await page.locator('.composer .paste-chip').waitFor();await page.locator('.composer .paste-chip button').first().click();assert(await page.locator('.paste-preview pre').textContent()===raw,'preview changed pasted bytes');await page.getByRole('button',{name:'Fermer',exact:true}).click();
 await page.waitForTimeout(350);const firstId=await page.evaluate(()=>JSON.parse(localStorage.getItem('solar.data.v3')).conversations[0].id);
 await page.locator('.new-thread').click();await input.fill('Brouillon B');await page.waitForTimeout(350);await page.getByRole('button',{name:'Bonjour Solar',exact:true}).click();assert((await input.inputValue()).includes('Passage retravaillé.'),'per-chat draft lost');assert(await page.locator('.composer .paste-chip').count()===1,'per-chat attachment lost');
 await page.reload();await page.getByRole('button',{name:'Bonjour Solar',exact:true}).click();assert((await input.inputValue()).includes('Passage retravaillé.'),'draft did not survive reload');assert(await page.locator('.composer .paste-chip').count()===1,'attachment did not survive reload');
 await input.press('Enter');await page.getByRole('button',{name:'Arrêter la génération'}).waitFor();await page.locator('.new-thread').click();await page.getByRole('button',{name:'Envoyer le message',exact:true}).waitFor();assert(await page.locator('.message').count()===0,'background answer leaked into new chat');
 const primary=requests.filter(r=>!r.messages[0].content.includes('Le champ « passage »'));assert(primary[1].model==='deep' && primary[1].max_tokens===4096,'next-turn selection not applied');assert(primary[1].messages.at(-1).content.includes(raw),'smart paste omitted or changed content');
 // Cmd K opens offline message search, keyboard Enter jumps to matching response.
 await input.press('Meta+k');await page.getByRole('combobox',{name:'Rechercher une conversation, un message'}).fill('HELICE');await page.locator('.search-result').first().waitFor();await page.screenshot({path:path.join(process.env.SOLAR_UI_SCREENSHOTS ?? '/tmp','solar-search.png')});await page.getByRole('combobox',{name:'Rechercher une conversation, un message'}).press('Enter');await page.locator('.message.highlighted').waitFor();assert(await page.locator('.message.highlighted').innerText().then(t=>t.includes('hélice')),'search jump wrong');
 await page.keyboard.press('Meta+k');await page.keyboard.press('Escape');assert(await page.getByRole('dialog',{name:'Recherche dans les conversations'}).count()===0,'Escape did not close search');
 // Persisted credential shows masked, read-only and is not replaced by dummy display.
 await page.getByRole('button',{name:'Paramètres',exact:true}).click();await page.locator('.provider-card').filter({hasText:'Fournisseur test'}).getByRole('button',{name:'Modifier',exact:true}).click();const key=page.getByRole('textbox',{name:'Clé API configurée'});await key.waitFor();assert(await key.getAttribute('type')==='password' && await key.getAttribute('readonly')!==null,'key not masked/read-only');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('solar.preview-vault.v2'))['provider:test'])==='non-sensitive-ui-fixture','masked dummy overwrote key');
 await page.getByRole('button',{name:'Apparence',exact:true}).click();await page.getByRole('button',{name:'Clair',exact:true}).click();await page.screenshot({path:path.join(process.env.SOLAR_UI_SCREENSHOTS ?? '/tmp','solar-settings-light.png')});await page.getByRole('button',{name:'Sombre',exact:true}).click();await page.getByRole('button',{name:'Retour au chat'}).click();
 // Auto-discovered local models, debounced prewarm, removed-model reconciliation.
 await page.locator('.model-control').click();await page.getByRole('button',{name:'local-a',exact:true}).click();await page.locator('.model-control').click();await page.getByRole('button',{name:'local-b',exact:true}).click();await page.waitForTimeout(1000);assert(preloads.length===1 && preloads[0].model==='local-b','preloading must debounce rapid changes and never preload cloud');assert(preloads[0].keep_alive==='5m','preload should expire');
 ollamaNames=['local-b'];await page.locator('.model-control').click();await page.getByRole('button',{name:'Actualiser Ollama',exact:true}).click();await page.getByRole('button',{name:'local-a',exact:true}).waitFor({state:'hidden'});assert(await page.getByRole('button',{name:'local-a',exact:true}).count()===0,'removed local model should not remain selectable');await page.keyboard.press('Escape');await page.getByRole('dialog',{name:'Choisir un modèle'}).waitFor({state:'hidden'});
 // Preload failure remains nonblocking; attachment conversion/removal and Stop work.
 memoryFailure=true;ollamaNames=['local-a','local-b'];await page.locator('.model-control').click();await page.getByRole('button',{name:'Actualiser Ollama',exact:true}).click();await page.getByRole('button',{name:'local-a',exact:true}).waitFor();await page.getByRole('button',{name:'local-a',exact:true}).click();await page.getByText('Indisponible',{exact:true}).waitFor();await input.fill('Question locale');assert(await page.getByRole('button',{name:'Envoyer le message',exact:true}).isEnabled(),'preload failure must not disable sending');await input.press('Enter');await page.getByRole('button',{name:'Envoyer le message',exact:true}).waitFor();assert(await page.locator('.message-content').last().innerText()==='Réponse locale','local chat should work despite preload failure');
 await input.fill('');await input.evaluate((el,text)=>{const data=new DataTransfer();data.setData('text/plain',text);el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));},raw);await page.locator('.composer .paste-chip button').first().click();await page.getByRole('button',{name:'Remettre dans le champ'}).click();assert(await input.inputValue()===raw,'expanding paste must preserve all bytes');assert(await page.locator('.composer .paste-chip').count()===0,'expanded chip should disappear');await input.fill('');await input.evaluate((el,text)=>{const data=new DataTransfer();data.setData('text/plain',text);el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));},raw);await page.locator('.composer').getByRole('button',{name:'Supprimer Code collé'}).click();assert(await page.locator('.composer .paste-chip').count()===0,'paste removal failed');
 await page.locator('.model-control').click();await page.getByRole('button',{name:'Modèle rapide',exact:true}).click();await input.fill('Interrompre cette réponse');await input.press('Enter');await page.getByRole('button',{name:'Arrêter la génération'}).waitFor();await page.getByRole('button',{name:'Arrêter la génération'}).click();await page.getByText('Réponse interrompue',{exact:true}).waitFor();
 const fallback=await context.newPage();await fallback.route('**/solar-ollama/api/tags',route=>route.fulfill({status:503,json:{error:'offline'}}));await fallback.goto('http://127.0.0.1:1421');await fallback.getByRole('textbox',{name:'Message à Solar'}).fill('Ollama absent');assert(await fallback.getByRole('button',{name:'Envoyer le message',exact:true}).isEnabled(),'unavailable Ollama must not block configured cloud');await fallback.close();
 await page.setViewportSize({width:390,height:700});await page.waitForTimeout(250);assert(await page.locator('.shell').evaluate(el=>el.classList.contains('collapsed')),'small viewport must auto-collapse');await page.getByRole('button',{name:'Afficher la barre latérale'}).click();await page.getByRole('button',{name:'Paramètres',exact:true}).click();await page.getByRole('button',{name:'Fournisseurs',exact:true}).click();await page.screenshot({path:path.join(process.env.SOLAR_UI_SCREENSHOTS ?? '/tmp','solar-mobile-settings.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile horizontal overflow');assert(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight),'outer document must not scroll');
 assert(errors.length===0,'browser errors: '+errors.join(';'));console.log('UI checks passed: streaming controls, snapshot isolation, Markdown, 5 text actions, paste preview/full send, persisted per-chat drafts/attachments, Cmd K accent search/jump, masked key, themes, Ollama detection/debounce/removal, responsive sidebar');
 await browser.close();await server.close();
})().catch(e=>{console.error(e);process.exit(1);});
