use std::{collections::HashMap, path::{Path,PathBuf}, sync::Mutex};
use serde::{Serialize,Deserialize};
use tauri_plugin_dialog::DialogExt;
#[derive(Default)] pub struct WorkState { roots:Mutex<HashMap<String,PathBuf>>, backups:Mutex<HashMap<String,Vec<Change>>> }
#[derive(Serialize)] pub struct Project { pub token:String, pub name:String, pub files:Vec<String> }
#[derive(Clone,Serialize,Deserialize)] pub struct Change { pub path:String, pub before:String, pub after:String }
fn allowed(name:&str)->bool { !name.starts_with('.') && !matches!(name,"node_modules"|"target"|"dist"|"build"|"vendor"|"Cargo.lock"|"package-lock.json") && !name.ends_with(".pem") && !name.ends_with(".key") && !name.to_lowercase().contains("credential") && !name.to_lowercase().contains("secret") }
fn scan(root:&Path,dir:&Path,out:&mut Vec<String>,depth:usize)->Result<(),String>{if depth>12||out.len()>=2000{return Ok(());}for entry in std::fs::read_dir(dir).map_err(|e|e.to_string())? {let entry=entry.map_err(|e|e.to_string())?;let name=entry.file_name().to_string_lossy().into_owned();if !allowed(&name){continue;}let kind=entry.file_type().map_err(|e|e.to_string())?;if kind.is_symlink(){continue;}if kind.is_dir(){scan(root,&entry.path(),out,depth+1)?;}else if kind.is_file() && entry.metadata().map_err(|e|e.to_string())?.len()<=512000 {out.push(entry.path().strip_prefix(root).map_err(|e|e.to_string())?.to_string_lossy().into_owned());}if out.len()>=2000{break;}}Ok(())}
fn root_for(state:&WorkState,token:&str)->Result<PathBuf,String>{state.roots.lock().map_err(|e|e.to_string())?.get(token).cloned().ok_or("Dossier non autorisé. Ouvre-le à nouveau.".into())}
fn checked(root:&Path,path:&str)->Result<PathBuf,String>{let rel=Path::new(path);if rel.is_absolute()||rel.components().any(|c| !matches!(c,std::path::Component::Normal(_))) {return Err("Chemin interdit".into());}let mut target=root.to_path_buf();for component in rel.components(){let name=component.as_os_str().to_string_lossy();if !allowed(&name){return Err("Fichier privé ou exclu".into());}target.push(component);let metadata=std::fs::symlink_metadata(&target).map_err(|e|e.to_string())?;if metadata.file_type().is_symlink(){return Err("Liens symboliques interdits".into());}}let real=target.canonicalize().map_err(|e|e.to_string())?;if !real.starts_with(root){return Err("Accès hors dossier interdit".into());}Ok(real)}
fn read(root:&Path,path:&str)->Result<String,String>{let target=checked(root,path)?;let metadata=std::fs::metadata(&target).map_err(|e|e.to_string())?;if !metadata.is_file()||metadata.len()>512000 {return Err("Fichier trop volumineux ou non régulier".into());}std::fs::read_to_string(target).map_err(|_|"Fichier binaire ou texte illisible".into())}
fn atomic_write(path:&Path,content:&str)->Result<(),String>{use std::io::Write;let parent=path.parent().ok_or("Chemin de fichier invalide")?;let temp=parent.join(format!(".solar-write-{}-{}",std::process::id(),std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map_err(|e|e.to_string())?.as_nanos()));let result=(||{let mut file=std::fs::OpenOptions::new().write(true).create_new(true).open(&temp).map_err(|e|e.to_string())?;file.write_all(content.as_bytes()).map_err(|e|e.to_string())?;file.sync_all().map_err(|e|e.to_string())?;std::fs::rename(&temp,path).map_err(|e|e.to_string())})();if result.is_err(){let _=std::fs::remove_file(&temp);}result}
fn transact(root:&Path,changes:&[Change])->Result<(),String>{let mut written:Vec<&Change>=vec![];for c in changes{let result=(||{let path=checked(root,&c.path)?;if read(root,&c.path)?!=c.before{return Err(format!("{} a changé depuis la confirmation",c.path));}atomic_write(&path,&c.after)})();if let Err(error)=result{let mut rollback_failed=false;for old in written.iter().rev(){if read(root,&old.path).ok().as_deref()!=Some(old.after.as_str()){rollback_failed=true;continue;}if checked(root,&old.path).and_then(|p|atomic_write(&p,&old.before)).is_err(){rollback_failed=true;}}return Err(if rollback_failed{format!("{} ; restauration incomplète, vérifie les fichiers avant de continuer",error)}else{error});}written.push(c);}Ok(())}
#[tauri::command] pub async fn work_open(app:tauri::AppHandle,state:tauri::State<'_,WorkState>)->Result<Option<Project>,String>{
 let selected=app.dialog().file().blocking_pick_folder();let Some(selected)=selected else{return Ok(None)};let root=selected.into_path().map_err(|e|e.to_string())?.canonicalize().map_err(|e|e.to_string())?;let name=root.file_name().unwrap_or_default().to_string_lossy().into_owned();let mut files=vec![];scan(&root,&root,&mut files,0)?;files.sort();let token=format!("{}-{}",std::process::id(),std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map_err(|e|e.to_string())?.as_nanos());let mut grants=state.roots.lock().map_err(|e|e.to_string())?;grants.clear();grants.insert(token.clone(),root);Ok(Some(Project{token,name,files}))
}
#[tauri::command] pub async fn work_read(state:tauri::State<'_,WorkState>,token:String,path:String)->Result<String,String>{read(&root_for(&state,&token)?,&path)}
#[tauri::command] pub async fn work_apply(app:tauri::AppHandle,state:tauri::State<'_,WorkState>,token:String,operation:String,changes:Vec<Change>)->Result<bool,String>{
 let root=root_for(&state,&token)?;if changes.is_empty()||changes.len()>20||changes.iter().map(|c|c.after.len()).sum::<usize>()>2000000{return Err("Lot de modifications invalide ou trop volumineux".into());}
 let mut seen=std::collections::HashSet::new();for c in &changes{if !seen.insert(&c.path){return Err("Chemin dupliqué".into());}if read(&root,&c.path)?!=c.before{return Err(format!("{} a changé depuis l’aperçu. Relis le fichier.",c.path));}}
 if !app.dialog().message(format!("Appliquer les modifications aux {} fichiers affichés dans l’aperçu ?",changes.len())).title("Solar Work").kind(tauri_plugin_dialog::MessageDialogKind::Warning).buttons(tauri_plugin_dialog::MessageDialogButtons::OkCancel).blocking_show(){return Ok(false);}
 transact(&root,&changes)?;
 state.backups.lock().map_err(|e|e.to_string())?.insert(format!("{}:{}",token,operation),changes);Ok(true)
}
#[tauri::command] pub async fn work_undo(app:tauri::AppHandle,state:tauri::State<'_,WorkState>,token:String,operation:String)->Result<bool,String>{let key=format!("{}:{}",token,operation);let changes=state.backups.lock().map_err(|e|e.to_string())?.get(&key).cloned().ok_or("Annulation indisponible après fermeture ou changement de dossier")?;let root=root_for(&state,&token)?;for c in &changes{if read(&root,&c.path)?!=c.after{return Err(format!("{} a été modifié depuis : annulation refusée",c.path));}}if !app.dialog().message("Restaurer les fichiers affichés à leur version précédente ?").title("Annuler dans Solar Work").buttons(tauri_plugin_dialog::MessageDialogButtons::OkCancel).blocking_show(){return Ok(false);}let reversed:Vec<Change>=changes.iter().map(|c|Change{path:c.path.clone(),before:c.after.clone(),after:c.before.clone()}).collect();transact(&root,&reversed)?;state.backups.lock().map_err(|e|e.to_string())?.remove(&key);Ok(true)}
#[cfg(test)] mod tests { use super::*; #[test] fn denies_paths_and_symlinks(){let root=std::env::temp_dir().join(format!("solar-work-{}",std::process::id()));std::fs::create_dir_all(&root).unwrap();std::fs::write(root.join("ok.txt"),"yes").unwrap();let real=root.canonicalize().unwrap();assert!(checked(&real,"../ok.txt").is_err());assert!(checked(&real,"/etc/passwd").is_err());assert!(read(&real,"ok.txt").is_ok());assert!(allowed(".env")==false);#[cfg(unix)]{std::os::unix::fs::symlink(root.join("ok.txt"),root.join("link.txt")).unwrap();assert!(checked(&real,"link.txt").is_err());}std::fs::remove_dir_all(root).unwrap();} }
