import { forwardRef, useEffect, useImperativeHandle, useRef, useState, type TextareaHTMLAttributes } from "react";
// Native text editing and selection remain intact; only the collapsed caret is drawn separately.
export const AnimatedTextarea = forwardRef<HTMLTextAreaElement,TextareaHTMLAttributes<HTMLTextAreaElement>>(function AnimatedTextarea(props,ref) {
 const area=useRef<HTMLTextAreaElement>(null);const mirror=useRef<HTMLDivElement>(null);const [caret,setCaret]=useState({x:0,y:0,height:22,visible:false});
 useImperativeHandle(ref,()=>area.current!,[]);
 const measure=()=>{const el=area.current;const box=mirror.current;if(!el||!box)return;const style=getComputedStyle(el);for(const key of ["fontFamily","fontSize","fontWeight","lineHeight","letterSpacing","paddingTop","paddingLeft","paddingRight","paddingBottom","tabSize"] as const)box.style[key]=style[key];box.style.width=`${el.clientWidth}px`;box.textContent=el.value.slice(0,el.selectionStart);const mark=document.createElement("span");mark.textContent="\u200b";box.appendChild(mark);const height=parseFloat(style.lineHeight)||22;setCaret({x:mark.offsetLeft-el.scrollLeft,y:mark.offsetTop-el.scrollTop,height,visible:document.activeElement===el && el.selectionStart===el.selectionEnd && mark.offsetTop-el.scrollTop>=0 && mark.offsetTop-el.scrollTop<el.clientHeight});};
 useEffect(()=>{measure();const observer=new ResizeObserver(measure);if(area.current)observer.observe(area.current);return()=>observer.disconnect();},[props.value]);
 return <div className="animated-input"><textarea {...props} ref={area} onFocus={e=>{props.onFocus?.(e);measure();}} onBlur={e=>{props.onBlur?.(e);setCaret(c=>({...c,visible:false}));}} onSelect={e=>{props.onSelect?.(e);measure();}} onScroll={e=>{props.onScroll?.(e);measure();}} onKeyUp={e=>{props.onKeyUp?.(e);measure();}}/><div ref={mirror} className="caret-mirror" aria-hidden="true"/>{caret.visible && <span className="animated-caret" aria-hidden="true" style={{left:caret.x,top:caret.y,height:caret.height}}/>}</div>;
});
