import { Button } from "./button";
import { Check, Monitor, Moon, Sun, RotateCcw } from "lucide-react";
import type { AppSettings, Palette } from "../../domain/types";
import { paletteFor, validColor } from "../../services/appearance";
import { resolveTheme } from "../../services/theme";
import { useState } from "react";
const names:Record<keyof Palette,string>={accent:"Couleur dominante",background:"Fond de l’interface",surface:"Surfaces et chatbox",text:"Texte",sidebar:"Barres latérales",userBubble:"Messages envoyés",border:"Bordures",selection:"Sélection et focus"};
export function AppearancePanel({settings,onSave}:{settings:AppSettings;onSave:(s:AppSettings)=>Promise<void>}) {
 const [editingTheme,setEditingTheme]=useState<"light"|"dark">(()=>resolveTheme(settings.theme));const p=paletteFor(settings,editingTheme);
 const color=(key:keyof Palette,value:string)=>{if(validColor(value))void onSave({...settings,appearance:{...settings.appearance,[editingTheme]:{...settings.appearance?.[editingTheme],[key]:value}}});};
 return <><div className="section-title"><div><h2>Apparence</h2><p>Ton espace, tes couleurs.</p></div></div><div className="visual-style"><h3>Style visuel</h3><div className="appearance-mode-row"><div><h4>Mode</h4><p>Automatique : clair de 6 h à 20 h, sombre de 20 h à 6 h.</p></div><div className="theme-options">{(["system","light","dark"] as const).map(theme=><button key={theme} className={`theme-card ${settings.theme===theme?"selected":""}`} aria-pressed={settings.theme===theme} aria-label={theme==="system"?"Automatique":theme==="dark"?"Sombre":"Clair"} onClick={()=>{if(theme!=="system")setEditingTheme(theme);void onSave({...settings,theme});}}><span className={`theme-preview ${theme==="system"?"automatic":theme}`}><i className="preview-sidebar"/><span className="preview-messages"><i/><i/><i/><i/></span><i className="preview-composer"/></span><span className="theme-caption">{theme==="system"?<Monitor size={14}/>:theme==="dark"?<Moon size={14}/>:<Sun size={14}/>}<span>{theme==="system"?"Automatique":theme==="dark"?"Sombre":"Clair"}</span>{settings.theme===theme&&<Check size={14}/>}</span></button>)}</div></div>
 <section className="glass-settings"><h3>Liquid Glass</h3><p>Règle séparément la transparence des zones. Dans l’application macOS, la transparence peut révéler le bureau derrière la fenêtre.</p>{([['glassRail','Barre des tâches'],['glassChat','Chat']] as const).map(([key,label])=><div className="color-row" key={key}><label htmlFor={key}>{label}</label><div><input id={key} type="range" min="0" max="100" value={settings.appearance?.[key]??0} onChange={e=>void onSave({...settings,appearance:{...settings.appearance,[key]:Number(e.target.value)}})}/><output htmlFor={key}>{settings.appearance?.[key]??0} %</output></div></div>)}</section>
 <div className="color-customization"><div className="palette-heading"><div><h3>Personnalisation</h3><p>Une palette indépendante pour chaque mode.</p></div><div className="palette-tabs">{(["light","dark"] as const).map(mode=><button key={mode} aria-label={mode==="light"?"Personnaliser les couleurs claires":"Personnaliser les couleurs sombres"} aria-pressed={editingTheme===mode} onClick={()=>setEditingTheme(mode)}>{mode==="light"?"Clair":"Sombre"}</button>)}</div></div>{(Object.keys(names) as (keyof Palette)[]).map(key=><div className="color-row" key={`${editingTheme}:${key}`}><label htmlFor={`color-${key}`}>{names[key]}</label><div><input id={`color-${key}`} type="color" aria-label={names[key]} value={p[key]} onChange={e=>color(key,e.target.value)}/><input className="hex-input" aria-label={`Code hexadécimal : ${names[key]}`} defaultValue={p[key]} key={p[key]} maxLength={7} onBlur={e=>{if(validColor(e.target.value))color(key,e.target.value);else e.target.value=p[key];}} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();}}/></div></div>)}<div className="color-row"><label htmlFor="corner-radius">Arrondi des surfaces</label><div><input id="corner-radius" type="range" min="12" max="36" value={settings.appearance?.radius??26} onChange={e=>void onSave({...settings,appearance:{...settings.appearance,radius:Number(e.target.value)}})}/><span>{settings.appearance?.radius??26} px</span></div></div><div className="color-row"><label htmlFor="appearance-font">Police d’écriture</label><select id="appearance-font" value={settings.appearance?.font??"system"} onChange={e=>void onSave({...settings,appearance:{...settings.appearance,font:e.target.value as "system"|"rounded"|"serif"}})}><option value="system">Système macOS</option><option value="rounded">Arrondie</option><option value="serif">Lecture classique</option></select></div><Button variant="outline" className="small-button reset-appearance" onClick={()=>void onSave({...settings,appearance:undefined})}><RotateCcw size={15}/>Réinitialiser l’apparence</Button></div></div></>;
}
