import { useEffect,useRef,useState } from "react";
import { Calculator, Check, FileText, Globe, Pencil, Terminal } from "lucide-react";
export function ComposerTools({read,write,web,workMode,onRead,onWrite,onWeb}:{read:boolean;write:boolean;web:boolean;workMode:boolean;onRead:()=>void;onWrite:()=>void;onWeb:()=>void}) {
 const [open,setOpen]=useState(false);const root=useRef<HTMLDivElement>(null);const trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const escape=(e:KeyboardEvent)=>{if(e.key==="Escape"&&open){setOpen(false);trigger.current?.focus();}};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",escape);};},[open]);
 const count=Number(read)+Number(workMode&&write)+Number(web);
 const items=[{name:"Lire des fichiers",icon:FileText,checked:read,click:onRead},{name:"Modifier des fichiers",icon:Pencil,checked:workMode&&write,click:onWrite,disabled:!workMode,hint:"Solar Code"},{name:"Utiliser le terminal",icon:Terminal,checked:false,disabled:true,hint:"Bientôt"},{name:"Chercher sur le web",icon:Globe,checked:web,click:onWeb},{name:"Calculer",icon:Calculator,checked:false,disabled:true,hint:"Bientôt"}];
 return <div ref={root} className="composer-tools"><button ref={trigger} type="button" className="tools-btn" aria-expanded={open} aria-controls="composer-tool-options" onClick={()=>setOpen(!open)}><Globe className="i sm"/><span key={count} className="bump">{count===0?"Aucun outil":`${count} outil${count>1?"s":""}`}</span></button><div id="composer-tool-options" className="pop" data-open={open} aria-label="Outils de Solar" {...(open?{}:{inert:""})}><p className="pop-title">Solar peut</p>{items.map((item,index)=><button type="button" key={item.name} className="pitem" style={{"--i":index} as React.CSSProperties} role="checkbox" aria-checked={item.checked} disabled={item.disabled} onClick={item.click}><item.icon className="i"/><span className="lbl">{item.name}{item.hint&&<small> · {item.hint}</small>}</span><span className="tick" aria-hidden="true"><Check/></span></button>)}</div></div>;
}
