import { useEffect,useState } from "react";
import { CheckCircle2, Square, PenLine } from "lucide-react";
import AnimatedShinyText from "./animated-text-01";
export type ComposerPhase="idle"|"thinking"|"writing"|"done"|"stopped";
const thinkingFr=["Solar réfléchit","Réflexion en cours","La réponse prend forme","Traitement de ta demande","Réflexion sur ta question","Préparation de la réponse","Ton message est en cours de traitement","Réponse en préparation","Le modèle réfléchit","Préparation en cours","Traitement du contexte","La réflexion se poursuit","Le modèle prépare sa réponse","Ta demande est prise en compte","Préparation du contenu"];
const writingFr=["Solar écrit","Rédaction en cours","La réponse s’écrit","Réception du texte","La réponse arrive","Le texte prend forme","La rédaction se poursuit","Le modèle rédige","Contenu en cours de génération","La réponse se construit"];
const thinkingEn=["Solar is thinking","Thinking in progress","The answer is taking shape","Processing your request","Thinking about your question","Preparing the answer","Your message is being processed","Answer in preparation","The model is thinking","Preparation in progress","Processing the context","Thinking continues","The model is preparing a response","Your request is being processed","Preparing the content"];
const writingEn=["Solar is writing","Writing in progress","The answer is being written","Receiving the text","The answer is arriving","The text is taking shape","Writing continues","The model is writing","Content is being generated","The answer is coming together"];
export function ComposerStatus({phase,model,elapsed,onStop,activity,lang="fr"}:{phase:ComposerPhase;model:string;elapsed:number;onStop:()=>void;activity?:string;lang?:"fr"|"en"}){
 const [open,setOpen]=useState(false);const [index,setIndex]=useState(0);
 const phrases=phase==="writing"?(lang==="fr"?writingFr:writingEn):(lang==="fr"?thinkingFr:thinkingEn);
 useEffect(()=>{setOpen(phase!=="idle");if(phase==="done"||phase==="stopped"){const timer=setTimeout(()=>setOpen(false),phase==="done"?2200:1400);return()=>clearTimeout(timer);}},[phase]);
 useEffect(()=>{setIndex(0);if(phase!=="thinking"&&phase!=="writing")return;let timer:ReturnType<typeof setTimeout>;const next=()=>{setIndex(old=>(old+1+Math.floor(Math.random()*(phrases.length-1)))%phrases.length);timer=setTimeout(next,2200+Math.random()*800);};timer=setTimeout(next,2200+Math.random()*800);return()=>clearTimeout(timer);},[phase,lang]);
 const busy=phase==="thinking"||phase==="writing";
 const phrase=phase==="done"?(lang==="fr"?"Réponse prête":"Answer ready"):phase==="stopped"?(lang==="fr"?"Génération arrêtée":"Stopped"):phase==="thinking"&&activity&&activity!=="thinking"?({searching:"Recherche Internet en cours",connecting:"Connexion au fournisseur",waiting:"En attente du modèle"}[activity]??"Préparation de la demande"):phrases[index%phrases.length];
 const sub=phase==="done"?`Terminé en ${elapsed} s`:phase==="stopped"?`Arrêté après ${elapsed} s`:`${model} · ${elapsed} s`;
 return <div className="sc-banner-wrap" data-open={open} aria-hidden={!open} {...(open?{}:{inert:""})}><div className="sc-banner-clip"><div className="sc-banner"><div className="sc-glyph" data-state={phase==="idle"?"thinking":phase} aria-hidden="true"><span className="sc-dots"><i/><i/><i/></span><PenLine className="sc-g-write"/><CheckCircle2 className="sc-g-done"/><Square className="sc-g-stop"/></div><div className="sc-texts"><p className="sc-b-title" role="status"><AnimatedShinyText key={phrase} className="sc-swap">{phrase}</AnimatedShinyText></p><p className="sc-b-sub">{sub}</p></div><button type="button" className="sc-stop" data-show={busy} disabled={!busy} onClick={onStop}>Stop</button></div></div></div>;
}
