import { useEffect, useRef, useState } from "react";
import { Button } from "./button";
import { Input } from "./input";
import { authorizeGmail,connectPlugin,disconnectPlugin,pluginIdentity,listPluginItems,readPluginItem,type PluginId,type PluginItem } from "../../services/pluginConnections";
export function PluginConnectionDialog({id,onClose,onImport}:{id:PluginId;onClose:()=>void;onImport:(text:string)=>Promise<void>}){
 const ref=useRef<HTMLDialogElement>(null);const [identity,setIdentity]=useState("");const [token,setToken]=useState("");const [busy,setBusy]=useState(false);const [query,setQuery]=useState("");const [items,setItems]=useState<PluginItem[]>([]);const [error,setError]=useState("");const [loaded,setLoaded]=useState(false);
 const name=id==="github"?"GitHub":"Gmail";
 useEffect(()=>{ref.current?.showModal();let live=true;void pluginIdentity(id).then(value=>{if(live)setIdentity(value);}).catch(()=>{});return()=>{live=false;};},[id]);
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError("");try{await action();}catch(e){setError(e instanceof Error?e.message:"Connexion impossible.");if(e instanceof Error&&/expirée/.test(e.message))setIdentity("");}finally{setBusy(false);}};
 return <dialog ref={ref} className="extension-dialog plugin-connection-dialog" aria-labelledby="plugin-connect-title" onCancel={onClose} onClose={onClose}><h2 id="plugin-connect-title"><img src={`/plugin-icons/${id}.svg`} alt=""/>{name}</h2><p>{identity?`Connecté : ${identity}`:id==="github"?"Connecte GitHub pour parcourir tes dépôts et joindre leur README à Solar.":"Autorise Solar à lire les e-mails que tu choisis. Les messages ne sont transmis à ton modèle qu’après ajout au chat et envoi."}</p>{!identity?<>{id==="gmail"&&<Button disabled={busy} onClick={()=>void run(async()=>setIdentity(await connectPlugin(id,await authorizeGmail())))}>Se connecter avec Google</Button>}{id==="github"?<><label>Jeton GitHub à accès limité<Input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder="github_pat_…"/></label><p className="settings-note">Choisis uniquement les dépôts utiles, avec Metadata et Contents en lecture. <a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">Créer un jeton</a></p><Button disabled={busy||!token.trim()} onClick={()=>void run(async()=>{setIdentity(await connectPlugin(id,token));setToken("");})}>Connecter GitHub</Button></>:<details><summary>Options avancées</summary><p>Autorisation OAuth Gmail avec la portée gmail.readonly. Elle expire et n’est conservée que pour cette session.</p><label>Jeton d’accès Gmail<Input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><Button disabled={busy||!token.trim()} onClick={()=>void run(async()=>{setIdentity(await connectPlugin(id,token));setToken("");})}>Vérifier et connecter</Button></details>}</>:<><form onSubmit={e=>{e.preventDefault();void run(async()=>{setItems(await listPluginItems(id,query));setLoaded(true);});}}><label>{id==="gmail"?"Rechercher des e-mails":"Rechercher un dépôt"}<Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={id==="gmail"?"is:unread, from:…":"Nom du dépôt"}/></label><Button disabled={busy} type="submit">{busy?"Chargement…":"Rechercher"}</Button></form><div className="plugin-connected-items">{items.map(item=><article key={item.id}><div><strong>{item.title}</strong><p>{item.detail}</p></div><Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{await onImport(await readPluginItem(id,item));onClose();})}>Ajouter au chat</Button></article>)}{loaded&&!items.length&&<p>Aucun résultat.</p>}</div><Button variant="ghost" disabled={busy} onClick={()=>void run(async()=>{await disconnectPlugin(id);setIdentity("");setItems([]);setLoaded(false);})}>Déconnecter {name}</Button></>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><Button variant="ghost" onClick={onClose}>Fermer</Button></div></dialog>;
}
