import { useEffect, useMemo, useRef, useState } from "react";
import { Search, MessageSquare } from "lucide-react";
import { solarStore } from "../../services/store";
import { buildSearchIndex, matchingParts, searchIndex, type SearchItem, type SearchResult } from "../../services/search";
function Highlight({ text, query }: { text: string; query: string }) { return <>{matchingParts(text,query).map((part,i) => part.match ? <mark key={i}>{part.text}</mark> : <span key={i}>{part.text}</span>)}</>; }
export function SearchPalette({ onClose, onOpen }: { onClose: () => void; onOpen: (conversationId: string, messageId?: string) => void }) {
  const [query,setQuery]=useState(""); const [index,setIndex]=useState<SearchItem[]>([]); const [selected,setSelected]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const input=useRef<HTMLInputElement>(null); const results=useMemo(()=>searchIndex(index,query),[index,query]); const previousFocus=useRef(document.activeElement as HTMLElement | null);
  useEffect(()=>{input.current?.focus(); let live=true; void (async()=>{try{const conversations=await solarStore.listConversations(); const groups=await Promise.all(conversations.map(c=>solarStore.listMessages(c.id))); if(live)setIndex(buildSearchIndex(conversations,groups.flat()));}catch{if(live)setError("Impossible de lire l’historique enregistré.");}finally{if(live)setLoading(false);}})();return()=>{live=false;previousFocus.current?.focus();};},[]);
  useEffect(()=>{setSelected(0);},[query]);
  useEffect(()=>{document.getElementById(`search-result-${selected}`)?.scrollIntoView({block:"nearest"});},[selected]);
  const open=(result:SearchResult)=>{onOpen(result.conversationId,result.messageId);onClose();};
  return <div className="palette-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className="search-palette" role="dialog" aria-modal="true" aria-label="Recherche dans les conversations" onKeyDown={event=>{if(event.key==="Escape"){event.preventDefault();onClose();}if(event.key==="ArrowDown" || event.key==="ArrowUp"){event.preventDefault();setSelected(i=>Math.max(0,Math.min(results.length-1,i+(event.key==="ArrowDown"?1:-1))));}if(event.key==="Enter" && results[selected]){event.preventDefault();open(results[selected]);}if(event.key==="Tab"){event.preventDefault();input.current?.focus();}}}>
    <label className="palette-input"><Search size={18}/><input ref={input} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Rechercher une conversation, un message…" aria-label="Rechercher une conversation, un message" aria-controls="search-results" aria-activedescendant={results[selected]?`search-result-${selected}`:undefined} role="combobox" aria-expanded="true" aria-autocomplete="list"/><kbd>⌘ K</kbd></label>
    <div id="search-results" className="palette-results" role="listbox" aria-label="Résultats"><p className="palette-caption">{query?"Résultats":"Conversations récentes"}</p>{results.map((result,i)=><button id={`search-result-${i}`} role="option" aria-selected={selected===i} className={`search-result ${selected===i?"selected":""}`} key={`${result.conversationId}:${result.messageId??"title"}`} onMouseEnter={()=>setSelected(i)} onClick={()=>open(result)} tabIndex={-1}><MessageSquare size={15}/><span><strong><Highlight text={result.title} query={query}/></strong>{result.excerpt && <small><Highlight text={result.excerpt} query={query}/></small>}</span><time>{new Intl.RelativeTimeFormat("fr",{numeric:"auto"}).format(-Math.max(0,Math.floor((Date.now()-Date.parse(result.updatedAt))/86400000)),"day")}</time></button>)}{!results.length && <p className="palette-empty" role="status">{loading?"Lecture de l’historique…":error|| (query?"Aucune conversation ou aucun message correspondant.":"Tes conversations apparaîtront ici.")}</p>}</div><footer>↑ ↓ Naviguer <span>↵ Ouvrir</span><span>esc Fermer</span></footer>
  </section></div>;
}
